import './global.css'
import type {Metadata} from 'next'
import React, {StrictMode} from "react";
import {Providers, ReduxProvider} from "@/app/providers";
import {Inter} from 'next/font/google'
import Head from "next/head";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Rei Music',
    description: 'Generated by create next app',
    icons: {
        icon: 'girl.jpg'
    }
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <html lang="zh">
        <body className={inter.className}>
        <StrictMode>
                <ReduxProvider>
                    {children}
                </ReduxProvider>
        </StrictMode>
        </body>
        </html>
    )
}
