import '@/app/ui/global.css'
import type {Metadata} from 'next'
import React, {StrictMode} from "react";
import ReduxProvider from "@/app/ui/redux-provider";

export const metadata: Metadata = {
  title: 'Rei Music',
  description: 'Generated by create next app',
  icons: {
    icon: 'girl.jpg'
  }
}
export default function RootLayout({children}: { children: React.ReactNode }) {

  return (
    <html lang="zh">
    <body>
    <StrictMode>
      <ReduxProvider>
        {children}
      </ReduxProvider>
    </StrictMode>
    </body>
    </html>
  )
}
